name: REMOTEBOT
on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/3 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      
      # BU ADIM LİSTEDE KESİNLİKLE GÖRÜNMELİ
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev pkg-config
      
      - name: Clean and Install
        run: |
          rm -rf node_modules package-lock.json
          npm install
          
      - run: node bot.js
